CREATE TABLE IF NOT EXISTS EMPLOYEES (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(128),
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS WORK_TIME (
    id INTEGER NOT NULL AUTO_INCREMENT,
    employee_id INTEGER NOT NULL,
    beginning_of_work TIMESTAMP,
    end_of_work TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES EMPLOYEES (id)
);