CREATE TABLE IF NOT EXISTS PRACOWNICY (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(128),
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS CZAS_PRACY (
    id INTEGER NOT NULL AUTO_INCREMENT,
    pracownik_id INTEGER NOT NULL,
    beginning_of_work TIMESTAMP,
    end_of_work TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (pracownik_id) REFERENCES "PRACOWNICY"(id)
);